id: P004212
initial_creation_type: ocr
created_at: 23/03/2020
last_modified_at: 2021-12-17 11:01:33.175609
source_metadata:
  id: bdr:W2CZ7846
  title: ཚུལ་ཁྲིམས་རྒྱ་མཚོའི་རྣམ་ཐར་
  author: ''
  volumes:
    f17d958c9a7b4361bd9ca9666b7223fc:
      image_group_id: I1KG2814
      title: ''
      volume_number: 1
      total_pages: 682
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
